### ISSUE TITLE
GDBrowser no longer works locally thanks to Cloudflare

### ISSUE THREAD

**Issue by PeacefulPotato** [GDColon/GDBrowser#168]
It looks like RobTop has decided to add [Cloudflare](https://www.unixsheikh.com/articles/stay-away-from-cloudflare.html) to the boomlings.com website so now nobody but Geometry Dash and apparently you can get to it. This means that you cannot locally install GDBrowser anymore as it just shows empty squares. See [these](https://lainsafe.delegao.moe/files/163037092634114.JPG) [screenshots](https://lainsafe.delegao.moe/files/163037100584755.JPG).

**Comment by GDColon** [comment]
Yeah this is a pretty big hecking issue. Hopefully we figure something out

**Comment by Reper2** [comment]
Last week there were a number of ddos on the GD servers and it took about 2 days for Rob to remove all of the ddos (he stayed up all night trying to fix the servers). This is probably the reason why he added Cloudflare to the boomlings.com website so that only the GD community has access to the website and to prevent future ddos.

**Comment by GDColon** [comment]
I found a very simple fix for this, it will be in the next commit~

**Comment by Reper2** [comment]
That's good! I still haven't even gotten a chance to use GDBrowser locally.

**Comment by PeacefulPotato** [comment]
Well, your fix worked, even though it shouldn't work as adding www still brings up Cloudflare. I don't know how you did it, but good job.

**Comment by PeacefulPotato** [comment]
Update: Looks like level downloading doesn't work anymore.
