### ISSUE TITLE
Incorrect behavior?

### ISSUE THREAD

**Issue by fancythedeveloper** [GDColon/GDBrowser#193]
I can't tell if this is intentional or not so I'm kind of just putting it here.

Anyways, when you put an ID in the search bar and click the user button, in-game it searches by User ID, but on GDBrowser it searches by Account ID.

For example: if you put 316 in-game, you'll get an account called [PIS](https://cdn.discordapp.com/attachments/777007609672237097/922567948890153010/unknown.png), but if you put 316 into GDBrowser, you'll get an account called [Zebratos](https://cdn.discordapp.com/attachments/777007609672237097/922568267262992384/unknown.png).
(Oh and I should mention this, but if you try searching just "316" without a space at the end on GDBrowser, you'll get the account NAMED 316, since it seems like GDBrowser also prioritizes names over IDs.)

**Comment by Silver-Volt4** [comment]
It appears that GDBrowser handles ID searching by requesting to getGJUserInfo20 with the parameters { targetAccountID: '316' }, which is Zebratos. The game handles ID searching by literally using the number as a search query, as shown in Wireshark:
![image](https://user-images.githubusercontent.com/35656715/147420452-cf84e054-2fdf-44bd-a96c-54d8527efdca.png)
Why it points to PIS instead of Zebratos is beyond my knowledge.
My guess is that Rob's servers store two different account identifiers, one is a user ID, one is an account ID. User ID's are probably for green players while account ID's are for golden players.

**Comment by Silver-Volt4** [comment]
hello senpai

**Comment by fancythedeveloper** [comment]
lol
