### ISSUE TITLE
Find better dragscroll script

### ISSUE THREAD

**Issue by GDColon** [GDColon/GDBrowser#25]
Find a script that supports drag scrolling (comments, searching, etc) but also allows you to select text.
(Is it normal to submit issues for your own project? I'm just doing this so I don't forget :P)

**Comment by Qufyy** [comment]
People can make those stuff for you with the issues so it's not bad. Not me though, not very experienced with JS :P

**Comment by 101arrowz** [comment]
I could do this but you need to tell Mr at what angle relative to vertical dragging should not be considered scrolling but rather selecting text.

**Comment by GDColon** [comment]
I tried `nochilddrag`, no luck.
Also, I guess 40-ish degrees works, but would it be possible to just cancel the dragscrolling if you're mousing over text? (mousing over = cursor changes to 𝙸)

**Comment by 101arrowz** [comment]
I tried to do some testing but I can't seem to find a way to get it to detect when it's highlighting text because jQuery puts in spaces and random other text in random nodes, so I can never tell if the node someone mouses over is actually text or not. This random hidden behavior is one of the reasons I don't like jQuery, but I'll try to find a workaround.
