### ISSUE TITLE
Cloudflare Pages support: I need help

### ISSUE THREAD

**Issue by masckmaster2007** [GDColon/GDBrowser#264]
Hello, I'm back, Replit is bad.
It's really slow just for 1 user and i wanted to try Cloudflare Pages.
**How do i set it up**
I tried using node forever on the build command and stuff so it runs on bg but i always get 404.
Yes, i used the subdomain port by Nadeway.
Here is the working version using Relpit: https://browse.dgdps.ix.tc
Here's the broken one on CF; https://browsecf.dgdps.ix.tc

**Comment by Nadwey** [comment]
Cloudflare Pages are for static content. You can't run a Node.js server using them.

**Comment by Nadwey** [comment]
However, if you really want to use cloudflare pages you could make another port (whole backend rewrite) that uses serverless functions https://developers.cloudflare.com/pages/platform/functions

(but you shouldn't because Colon wants to [rewrite everything from scratch](https://github.com/GDColon/GDBrowser/issues/245#issuecomment-1155862578))

**Comment by masckmaster2007** [comment]
f

**Comment by Nadwey** [comment]
f
