### ISSUE TITLE
Using a CDN to improve load time

### ISSUE THREAD

**Issue by SeeBeyondDev** [GDColon/GDBrowser#33]
If the server ever gets very overloaded, something that can help loading assets and fonts is a CDN. I use a [CDN Bunny](https://bunnycdn.com/) which is very inexpensive. In fact, my credits for my CDN account are hardly depleted even though I use the CDN for 5 different sites! If you wanted a CDN, you could use my account if you wanted to save on the $10 minimum account deposit which you will definitely not need to use all of (I speak from experience.)

**Comment by GDColon** [comment]
This seems a little overkill to me

**Comment by 101arrowz** [comment]
@SeeBeyondDev This is a good idea but using a CDN involves separating the server-side API and the HTML, which is something that could be done but would require a complete overhaul of the backend.

You seem to be thinking about the modern type of web app in general actually, which is the Node.js backend, NGINX or a CDN for serving static content, no SSR, and a single-page PWA. I've suggested doing these things to @GDColon but (unless he's changed his mind since #13) is not something that's planned for this project.
