### ISSUE TITLE
Analasys still broken in Edge

### ISSUE THREAD

**Issue by siky112** [GDColon/GDBrowser#35]
I think you forgot to test lol
(Both pictures on level easy)
![gdbrowserbug8](https://user-images.githubusercontent.com/20342336/68536266-01e92d80-0305-11ea-81a3-e245bd1534d9.PNG)
![gdbrowserbug9](https://user-images.githubusercontent.com/20342336/68536269-0b729580-0305-11ea-9481-0a1b598d5d29.PNG)

**Comment by GDColon** [comment]
I have no idea how to fix this. Folks?

**Comment by Altenhh** [comment]
i'd just ignore all edge issues, they're not really all that important.
but are you on Edge v12?

**Comment by SeeBeyondDev** [comment]
I also second, not because of it not being important but edge is switching to chromium soon so if it works on chrome it will work on edge. This issue will resolve itself in due time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GDColon** [comment]
Edge? To Chromium? What is this timeline anymore?

**Comment by Altenhh** [comment]
[this](https://www.youtube.com/watch?v=-ZsLZez3vSw) explains everything on why Edge is switching to Chromium

**Comment by 101arrowz** [comment]
Thinking Edge is unimportant is quite naive if you ask me. About 6% of all internet users use Edge, and with quite a bit of our userbase being young children without much knowledge/ability to use browsers other than the ones that are installed by default, I would say that figure jumps to about 10% or maybe even 15%. Also, there is no assurance that everyone will upgrade to Edge using Chromium. Internet Explorer still has more market share than Edge because people don't like to upgrade and change things.

The way to solve this, as I've said before, is to explicitly set the height to something other than `auto` for the images inside that `div`. Like, for example, `75%`.
